#!/usr/bin/env bash
# Custom completion scripts. Loaded by `bash-completion`

## SYSTEM
for i in /etc/bash_completion.d/*; do
    [[ ${i##*/} != @($_backup_glob|Makefile*|$_blacklist_glob) && -f \
    $i && -r $i ]] && source "$i"
done

## HOMEBREW
export BASH_COMPLETION_COMPAT_DIR="${HOMEBREW_PREFIX}/etc/bash_completion.d"

## HASHICORP
[[ -x "$(command -v terraform)" ]] && complete -C "$(command -v terraform)" terraform
[[ -x "$(command -v vault)" ]] && complete -C "$(command -v vault)" vault

## FLUX
[[ -x "$(command -v flux)" ]] && source <(flux completion bash)

## COMPLETE-ALIAS
## https://github.com/cykerway/complete-alias/blob/master/complete_alias
source $HOME/src/complete-alias/complete_alias
complete -F _complete_alias kc

## AWSCLI
complete -C '/usr/local/bin/aws_completer' aws
