#!/usr/bin/env bash
# Custom completion scripts. Loaded by `bash-completion`

## HASHICORP
[[ -x "$(command -v terraform)" ]] && complete -C "$(command -v terraform)" terraform
[[ -x "$(command -v vault)" ]] && complete -C "$(command -v vault)" vault
