# Use custom format
# format = """
# [┌───────────────────>](bold green)
# [│](bold green)$directory$rust$package
# [└─>](bold green) """

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Inserts a blank line between shell prompts
add_newline = true

[character]
success_symbol = "[❯](bold purple)"
error_symbol   = "[❯](bold red)"
vicmd_symbol   = "[❮](bold purple)"

[cmd_duration]
disabled = true

[directory]
style             = "bold blue"
truncation_length = 5
truncate_to_repo  = true

[kubernetes]
disabled = true

[terraform]
style    = "bold cyan"
disabled = false

[time]
disabled = true
